version: "2"
services:
  web:
    #image: yutaf/convox-rails-bootstrap
    build: rails
    ports:
    - '80:3000'
    volumes:
      # To create a rails myapp project under /srv directory in the container at the begginig, bootstrapping
      #- ./rails:/srv
      - ./rails/myapp:/app
    # Below part is for convox rails to work with nginx(but it did not work well)
#    volumes_from:
#      - public-data
#    environment:
#      PORT: 4001
#  nginx:
#    build: rails/myapp/containers/nginx
#    volumes_from:
#      - public-data
#    ports:
#      - '80:80'
#    depends_on:
#      - web
#  public-data:
#    image: busybox
#    volumes:
#      - ./rails/myapp/public:/app/public
